### ISSUE TITLE
Multiple errors on raspberry pi

### ISSUE THREAD

**Issue by mannueltuttu** [Cqsi/lichess_terminal#53]
Hi 
I am able to install the application using instructions given.I am able to give lichess api key also but aftter that it is giving me constant errors i have included here

```
Traceback (most recent call last):
  File "/home/pi/.local/bin/lichs", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/lichs/__main__.py", line 44, in main
    account_data = client.account.get()
  File "/home/pi/.local/lib/python3.7/site-packages/berserk/clients.py", line 115, in get
    return self._r.get(path, converter=models.Account.convert)
  File "/home/pi/.local/lib/python3.7/site-packages/berserk/session.py", line 60, in get
    return self.request('GET', *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/berserk/session.py", line 56, in request
    return fmt.handle(response, is_stream=is_stream, converter=converter)
  File "/home/pi/.local/lib/python3.7/site-packages/berserk/formats.py", line 35, in handle
    return converter(self.parse(response))
  File "/home/pi/.local/lib/python3.7/site-packages/berserk/formats.py", line 76, in parse
    return response.json(cls=self.decoder)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 889, in json
    self.content.decode(encoding), **kwargs
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 535, in loads
    return cls(encoding=encoding, **kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'encoding'

```

**Comment by Cqsi** [comment]
Hey there,

Sorry for the delayed response. Can you describe the problem in a bit more detail? When exactly does the problem occur?

**Comment by mannueltuttu** [comment]
I have used this programme on raspberry pi 3a+ running raspbian os 32bit (tried it with 64bit archlinux also).While installation went smooth .I have used git clone and used 
pip3 install recommended.txt first followed by installataion of lichs as per ur documents.
When i run the programme it ask for the api key which I enter follwed by above mentioned error

My python version is 3.7 

I have tried uninstalling berserk and using berserk-downstream also both give same result.

**Comment by ljensen3** [comment]
Hello, did yall ever get this working? I also have this error

**Comment by Cqsi** [comment]
@ljensen3 not to my knowledge. I'm quite busy currently, but I will try to look into it when I have time.
